android:
  image: ubuntu:latest
  packages:
    - bc
    - bison
    - build-essential
    - curl
    - flex
    - g++
    - gcc
    - git
    - libssl-dev
    - libxml2-utils
    - make
    - python
    - unzip
    - xmlstarlet
  tasks:
    build:
      env:
        CIRRUS_ARTIFACT_NAME: los-recovery.img
      steps:
        - run: |
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            export PATH=~/bin:$PATH
        - run: ./sync-repo.sh
        - run: ./build-image.sh
        - run: ./upload-artifact.sh
