android:
  image: ubuntu:latest
  packages:
    - bc
    - bison
    - build-essential
    - curl
    - flex
    - g++
    - gcc
    - git
    - libssl-dev
    - libxml2-utils
    - make
    - python
    - unzip
    - xmlstarlet
  tasks:
    build:
      env:
        CIRRUS_ARTIFACT_NAME: los-recovery.img
      steps:
        - run: |
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            export PATH=~/bin:$PATH
        - run: repo init -u git://github.com/LineageOS/android.git -b lineage-20.0
        - run: repo sync -j$(nproc --all) --force-sync
        - run: source build/envsetup.sh
        - run: lunch lineage_RE879EL1-userdebug
        - run: mka bootimage
        - run: |
            echo "Uploading recovery image..."
            curl -X POST \
              -H "Authorization: Bearer $CIRRUS_API_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@out/target/product/RE879EL1/boot.img" \
              "https://api.cirrus-ci.com/v1/artifact/build/$CIRRUS_ARTIFACT_NAME"
